using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Text.Json.Serialization;
using BepInEx;
using Unity.Mathematics;
using VAutomationCore.Core.Config;
using VAuto.Zone.Core;
using VAuto.Zone.Models;

namespace VAuto.Zone.Services
{
    /// <summary>
    /// Service for managing zone configurations from JSON.
    /// </summary>
    public static class ZoneConfigService
    {
        private const string GlowLibraryZoneId = "glow_library";
        private const int DefaultBorderCarpetPrefabId = 1144832236; // PurpleCarpetsBuildMenuGroup01
        private const int DefaultBorderGlowPrefabId = -1408736701; // eSwatch_Color_StrongbladeDLC_ModularCarpets
        private const string DefaultBorderCarpetPrefabName = "PurpleCarpetsBuildMenuGroup01";
        private const string DefaultBorderGlowPrefabName = "eSwatch_Color_StrongbladeDLC_ModularCarpets";
        private static ZonesConfig _zonesConfig;
        private static readonly string ConfigPath = VAutoPathMap.GetConfigFile(VAutoModule.Zone, "VAuto.Zones.json");
        private static bool _initialized;

        /// <summary>
        /// Initialize the zone service and load configuration.
        /// </summary>
        public static void Initialize()
        {
            if (_initialized) return;
            
            LoadZonesConfig();
            _initialized = true;
            ZoneCore.LogInfo($"[ZoneConfigService] Initialized with {GetZoneCount()} zones");
        }

        /// <summary>
        /// Load zones configuration from JSON file.
        /// </summary>
        private static void LoadZonesConfig()
        {
            try
            {
                if (File.Exists(ConfigPath))
                {
                    var json = File.ReadAllText(ConfigPath);
                    _zonesConfig = JsonSerializer.Deserialize<ZonesConfig>(json, ZoneJsonOptions.WithUnityMathConverters);
                    
                    var count = _zonesConfig?.Zones?.Count ?? 0;
                    ZoneCore.LogInfo($"[ZoneConfigService] Loaded {count} zones from {ConfigPath}");
                    
                    if (!string.IsNullOrEmpty(_zonesConfig?.Description))
                    {
                        ZoneCore.LogInfo($"[ZoneConfigService] Description: {_zonesConfig.Description}");
                    }
                    
                    // Log loaded zones
                    foreach (var zone in GetAllZones())
                    {
                        var templateCount = GetBuildTemplatesForZone(zone.Id).Count;
                        ZoneCore.LogInfo($"[ZoneConfigService]   Zone '{zone.Id}' ({zone.DisplayName}): {zone.Shape} at ({zone.CenterX}, {zone.CenterZ}) r={zone.Radius}, Kit={zone.KitToApplyId ?? "none"}, Templates={templateCount}");
                    }

                    EnsureGlowLibraryZone();
                }
                else
                {
                    _zonesConfig = new ZonesConfig();
                    ZoneCore.LogInfo($"[ZoneConfigService] Zones config missing at {ConfigPath}; seeding defaults.");
                    CreateDefaultZonesConfig();
                }
            }
            catch (Exception ex)
            {
                ZoneCore.LogError($"[ZoneConfigService] Failed to load zones: {ex.Message}");
                _zonesConfig = new ZonesConfig();
            }
        }

        /// <summary>
        /// Create default zones configuration if file doesn't exist.
        /// </summary>
        private static void CreateDefaultZonesConfig()
        {
            try
            {
                var defaultZones = new ZonesConfig
                {
                    Description = "Default zones generated by VAutoZone",
                    DefaultKitId = "Kit1",
                    DefaultZoneId = string.Empty,
                    DefaultTeleport = new float3(-2657.5f, 10f, -987.5f),
                    Zones = new List<ZoneDefinition>
                    {
                        new ZoneDefinition
                        {
                            Id = "default_safezone",
                            DisplayName = "Default Safe Zone",
                            Shape = "Circle",
                            CenterX = 0f,
                            CenterZ = 0f,
                            Radius = 50f,
                            KitToApplyId = null,
                            GlowEffectColorHex = "#00FF00",
                            GlowPrefabId = DefaultBorderCarpetPrefabId,
                            GlowPrefab = DefaultBorderCarpetPrefabName,
                            BorderGlowPrefabId = DefaultBorderGlowPrefabId,
                            BorderGlowPrefab = DefaultBorderGlowPrefabName,
                            AutoGlowWithZone = true,
                            EnterMessage = "You entered a safe zone.",
                            ExitMessage = "You left a safe zone.",
                            TeleportOnEnter = false,
                            ReturnOnExit = false
                        },
                        new ZoneDefinition
                        {
                            Id = GlowLibraryZoneId,
                            DisplayName = "Glow Library Zone",
                            Shape = "Circle",
                            CenterX = -2657.5f,
                            CenterZ = -987.5f,
                            Radius = 120f,
                            KitToApplyId = null,
                            GlowEffectColorHex = "#FFD700",
                            GlowPrefabId = DefaultBorderCarpetPrefabId,
                            GlowPrefab = DefaultBorderCarpetPrefabName,
                            BorderGlowPrefabId = DefaultBorderGlowPrefabId,
                            BorderGlowPrefab = DefaultBorderGlowPrefabName,
                            GlowSpawnHeight = 0.3f,
                            AutoGlowWithZone = true,
                            EnterMessage = "Entered Glow Library zone.",
                            ExitMessage = "Exited Glow Library zone.",
                            TeleportOnEnter = true,
                            TeleportX = -2657.5f,
                            TeleportY = 10f,
                            TeleportZ = -987.5f,
                            ReturnOnExit = true
                        }
                    }
                };
                
                var directory = Path.GetDirectoryName(ConfigPath);
                if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
                {
                    Directory.CreateDirectory(directory);
                }
                
                var options = ZoneJsonOptions.WithUnityMathConverters;
                options.WriteIndented = true;
                var json = JsonSerializer.Serialize(defaultZones, options);
                File.WriteAllText(ConfigPath, json);
                _zonesConfig = defaultZones;
                ZoneCore.LogInfo($"[ZoneConfigService] Created default zones config at {ConfigPath}");
            }
            catch (Exception ex)
            {
                ZoneCore.LogError($"[ZoneConfigService] Failed to create default config: {ex.Message}");
            }
        }

        private static void EnsureGlowLibraryZone()
        {
            try
            {
                _zonesConfig ??= new ZonesConfig();
                _zonesConfig.Zones ??= new List<ZoneDefinition>();
                if (string.IsNullOrWhiteSpace(_zonesConfig.DefaultKitId))
                {
                    _zonesConfig.DefaultKitId = "Kit1";
                }
                _zonesConfig.DefaultZoneId ??= string.Empty;

                foreach (var zone in _zonesConfig.Zones)
                {
                    if (zone != null && zone.Id.Equals(GlowLibraryZoneId, StringComparison.OrdinalIgnoreCase))
                    {
                        return;
                    }
                }

                _zonesConfig.Zones.Add(new ZoneDefinition
                {
                    Id = GlowLibraryZoneId,
                    DisplayName = "Glow Library Zone",
                    Shape = "Circle",
                    CenterX = -2657.5f,
                    CenterZ = -987.5f,
                    Radius = 120f,
                    KitToApplyId = null,
                    GlowEffectColorHex = "#FFD700",
                    GlowPrefabId = DefaultBorderCarpetPrefabId,
                    GlowPrefab = DefaultBorderCarpetPrefabName,
                    BorderGlowPrefabId = DefaultBorderGlowPrefabId,
                    BorderGlowPrefab = DefaultBorderGlowPrefabName,
                    GlowSpawnHeight = 0.3f,
                    AutoGlowWithZone = true,
                    EnterMessage = "Entered Glow Library zone.",
                    ExitMessage = "Exited Glow Library zone.",
                    TeleportOnEnter = true,
                    TeleportX = -2657.5f,
                    TeleportY = 10f,
                    TeleportZ = -987.5f,
                    ReturnOnExit = true
                });

                var options = ZoneJsonOptions.WithUnityMathConverters;
                options.WriteIndented = true;
                File.WriteAllText(ConfigPath, JsonSerializer.Serialize(_zonesConfig, options));
                ZoneCore.LogInfo($"[ZoneConfigService] Added missing built-in zone '{GlowLibraryZoneId}'");
            }
            catch (Exception ex)
            {
                ZoneCore.LogError($"[ZoneConfigService] Failed to ensure glow library zone: {ex.Message}");
            }
        }

        /// <summary>
        /// Get all zones.
        /// </summary>
        public static List<ZoneDefinition> GetAllZones()
        {
            return _zonesConfig?.Zones ?? new List<ZoneDefinition>();
        }

        /// <summary>
        /// Get zone by ID.
        /// </summary>
        public static ZoneDefinition GetZoneById(string zoneId)
        {
            if (_zonesConfig?.Zones == null) return null;
            
            foreach (var zone in _zonesConfig.Zones)
            {
                if (zone.Id.Equals(zoneId, StringComparison.OrdinalIgnoreCase))
                {
                    return zone;
                }
            }
            
            return null;
        }

        /// <summary>
        /// Find zone at position.
        /// </summary>
        public static ZoneDefinition GetZoneAtPosition(float x, float z)
        {
            if (_zonesConfig?.Zones == null) return null;

            var defaultZone = GetDefaultZone();
            if (defaultZone != null && defaultZone.IsInside(x, z))
            {
                return defaultZone;
            }

            foreach (var zone in _zonesConfig.Zones)
            {
                if (defaultZone != null && string.Equals(zone.Id, defaultZone.Id, StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                if (zone.IsInside(x, z))
                {
                    return zone;
                }
            }
            
            return null;
        }

        /// <summary>
        /// Get number of loaded zones.
        /// </summary>
        public static int GetZoneCount()
        {
            return _zonesConfig?.Zones?.Count ?? 0;
        }

        /// <summary>
        /// Get kit ID for a zone.
        /// </summary>
        public static string GetKitIdForZone(string zoneId)
        {
            var zone = GetZoneById(zoneId);
            return zone?.KitToApplyId;
        }

        public static string GetDefaultKitId()
        {
            return _zonesConfig?.DefaultKitId;
        }

        public static string GetDefaultZoneId()
        {
            return _zonesConfig?.DefaultZoneId ?? string.Empty;
        }

        public static ZoneDefinition GetDefaultZone()
        {
            var id = GetDefaultZoneId();
            if (string.IsNullOrWhiteSpace(id))
            {
                return null;
            }

            return GetZoneById(id);
        }

        public static bool HasDefaultZone()
        {
            return GetDefaultZone() != null;
        }

        public static bool SetDefaultZoneId(string zoneId)
        {
            if (string.IsNullOrWhiteSpace(zoneId))
            {
                return false;
            }

            var zone = GetZoneById(zoneId);
            if (zone == null)
            {
                return false;
            }

            _zonesConfig ??= new ZonesConfig();
            _zonesConfig.DefaultZoneId = zone.Id;
            return SaveZonesConfig();
        }

        public static List<string> GetSchematicsForZone(string zoneId)
        {
            var zone = GetZoneById(zoneId);
            return zone?.Schematics ?? new List<string>();
        }

        public static List<string> GetBuildTemplatesForZone(string zoneId)
        {
            var zone = GetZoneById(zoneId);
            if (zone == null)
            {
                return new List<string>();
            }

            if (zone.Templates != null && zone.Templates.Count > 0)
            {
                return zone.Templates;
            }

            // Backward compatibility for older config naming.
            return zone.Schematics ?? new List<string>();
        }

        public static bool TryGetTeleportPointForZone(string zoneId, out float x, out float y, out float z)
        {
            x = y = z = 0f;
            var zone = GetZoneById(zoneId);
            if (zone == null)
            {
                return false;
            }

            if (!zone.TeleportOnEnter)
            {
                return false;
            }

            // If zone teleport position is left empty, use full global default vector.
            if (zone.TeleportX == 0f && zone.TeleportY == 0f && zone.TeleportZ == 0f)
            {
                var fallback = _zonesConfig?.DefaultTeleport ?? new float3(-2657.5f, 10f, -987.5f);
                x = fallback.x;
                y = fallback.y;
                z = fallback.z;
                return true;
            }

                x = zone.TeleportX;
                y = zone.TeleportY;
                z = zone.TeleportZ;
                return true;
            }

        public static bool ShouldReturnOnExit(string zoneId)
        {
            var zone = GetZoneById(zoneId);
            return zone?.ReturnOnExit ?? false;
        }

        /// <summary>
        /// Get glow color for a zone.
        /// </summary>
        public static string GetGlowColorForZone(string zoneId)
        {
            var zone = GetZoneById(zoneId);
            return zone?.GlowEffectColorHex;
        }

        /// <summary>
        /// Get glow prefab ID for a zone.
        /// </summary>
        public static int GetGlowPrefabIdForZone(string zoneId)
        {
            var zone = GetZoneById(zoneId);
            return zone?.GlowPrefabId ?? 0;
        }

        /// <summary>
        /// Get glow spawn height for a zone.
        /// </summary>
        public static float GetGlowSpawnHeightForZone(string zoneId)
        {
            var zone = GetZoneById(zoneId);
            return zone?.GlowSpawnHeight ?? 0f;
        }

        public static bool IsAutoGlowEnabledForZone(string zoneId)
        {
            var zone = GetZoneById(zoneId);
            return zone?.AutoGlowWithZone ?? false;
        }

        public static bool SetAutoGlowForZone(string zoneId, bool enabled)
        {
            var zone = GetZoneById(zoneId);
            if (zone == null)
            {
                return false;
            }

            zone.AutoGlowWithZone = enabled;
            return SaveZonesConfig();
        }

        public static bool SaveZonesConfig()
        {
            try
            {
                var options = ZoneJsonOptions.WithUnityMathConverters;
                options.WriteIndented = true;
                var json = JsonSerializer.Serialize(_zonesConfig ?? new ZonesConfig(), options);
                File.WriteAllText(ConfigPath, json);
                return true;
            }
            catch (Exception ex)
            {
                ZoneCore.LogError($"[ZoneConfigService] Failed to save zones config: {ex.Message}");
                return false;
            }
        }

        /// <summary>
        /// Get enter message for a zone.
        /// </summary>
        public static string GetEnterMessageForZone(string zoneId)
        {
            var zone = GetZoneById(zoneId);
            return zone?.EnterMessage;
        }

        /// <summary>
        /// Get exit message for a zone.
        /// </summary>
        public static string GetExitMessageForZone(string zoneId)
        {
            var zone = GetZoneById(zoneId);
            return zone?.ExitMessage;
        }

        /// <summary>
        /// Reload zones configuration.
        /// </summary>
        public static void Reload()
        {
            _initialized = false;
            Initialize();
            ZoneCore.LogInfo("[ZoneConfigService] Configuration reloaded");
        }
    }
}
